//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_controledeponto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_controledeponto()
        {
            this.tb_folhapagamento = new HashSet<tb_folhapagamento>();
        }
    
        public int id_controleDePonto { get; set; }
        public int id_funcionario { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime dt_mes { get; set; }
        public Nullable<System.DateTime> dt_entrada { get; set; }
        public Nullable<System.DateTime> dt_saida { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folhapagamento> tb_folhapagamento { get; set; }
    }
}
