//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcionario()
        {
            this.tb_controledeponto = new HashSet<tb_controledeponto>();
            this.tb_folhapagamento = new HashSet<tb_folhapagamento>();
        }
    
        public int id_funcionario { get; set; }
        public int id_usuario { get; set; }
        public string nm_funcionario { get; set; }
        public string ds_cpf { get; set; }
        public string ds_email { get; set; }
        public string ds_cargo { get; set; }
        public decimal vl_salario { get; set; }
        public System.TimeSpan tm_horasTrabalhadas { get; set; }
        public System.DateTime dt_contratacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_controledeponto> tb_controledeponto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_folhapagamento> tb_folhapagamento { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
