//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        public int id_fornecedor { get; set; }
        public string nm_fornecedor { get; set; }
        public string nm_empresa { get; set; }
        public string ds_telefone { get; set; }
        public string ds_celular { get; set; }
        public string ds_endereco { get; set; }
        public int id_produto { get; set; }
        public int id_estoque { get; set; }
    
        public virtual tb_estoque tb_estoque { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
