//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_folhapagamento
    {
        public int id_folhaPagamento { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<int> id_controleDePonto { get; set; }
        public Nullable<System.DateTime> dt_mes { get; set; }
        public Nullable<decimal> vl_salario { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public Nullable<decimal> vl_contribuicao { get; set; }
        public Nullable<decimal> vl_total { get; set; }
    
        public virtual tb_controledeponto tb_controledeponto { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
