//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log
    {
        public int id_log { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> dt_dataLogin { get; set; }
        public string ds_telaEntrou { get; set; }
        public string ds_oqFez { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
