//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pedido_compra()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_pedido_compra { get; set; }
        public int id_fornecedor { get; set; }
        public int id_produto { get; set; }
        public Nullable<System.DateTime> dt_pedido { get; set; }
        public Nullable<System.DateTime> dt_prevista { get; set; }
        public int qtd_produto { get; set; }
        public decimal vl_valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
