//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda_item
    {
        public int id_venda_item { get; set; }
        public Nullable<int> id_venda { get; set; }
        public Nullable<int> id_produto { get; set; }
    
        public virtual tb_produto tb_produto { get; set; }
        public virtual tb_venda tb_venda { get; set; }
    }
}
